FROM golang:1.24-alpine

RUN apk add --no-cache tini bash curl

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY test test

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["bash", "-c", "sleep infinity"]
